"""Ajout de la colonne subject à la table grade

Revision ID: e27434d90464
Revises: 5edd7aba16cc
Create Date: 2025-04-21 11:55:02.134076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27434d90464'
down_revision = '5edd7aba16cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))
        batch_op.drop_column('course')
        batch_op.drop_column('grade')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('score')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
